<?php

function twitterForm($place, $city)
{
echo "

	<img id='top' src='top.png' alt=''> 
	<div id='form_container'>
		<form id='form_18863' class='appnitro'  method='post' action='http://localhost/assignment/twitter/form/twitterPost.php'>
					<div class='form_description'>
			<h2>Make a comment!</h2>
			<p>Have you visited this place before? What did you think? Type a comment below and we'll post it to Twitter!</p>
		</div>						
		<label class='description' for='element_1'>Name: </label>
		<div>
			<input id='element_1' name='element_1' class='element text medium' type='text' maxlength='20' value=''/> 
		</div> 
		<label class='description' for='element_2'>Comment: </label>
		<div>
			<textarea id='element_2' name='element_2' class='element textarea small' maxlength='200'></textarea> 
		</div><p class='guidelines' id='guide_2'><small>Max 200 characters</small></p> 
			
			    <input type='hidden' name='place' value='" . $place . "' />
			    <input type='hidden' name='city' value='" . $city . "' />

				<input id='saveForm' class='button_text' type='submit' name='submit' value='Submit' />

		</form>	
		<div id='footer'>
			Generated by <a href='http://www.phpform.org'>pForm</a>
		</div>
	</div>
	<img id='bottom' src='bottom.png' alt=''>

</html>";
}