<?php

  function twitterWidgetComplete($place, $city, $n, $connection)
  {
    #hide errors
    error_reporting(0);
    ini_set('display_errors', 0);
	
	if($place != $city) {
		$height = "1000";
	}
	else {
		$height = "500";
	}
	
	#carosel js
    echo "
      <link rel='stylesheet' href='https://localhost/assignment/twitter/carosel.css'>
      <script>
      function showSlides() {
	
      var i;
      var slides = document.getElementsByClassName('mySlides');
      var dots = document.getElementsByClassName('dot');
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = 'none';  
      }
      slideIndex++;
      if (slideIndex > slides.length) {slideIndex = 1}    
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(' active', '');
      }
      slides[slideIndex-1].style.display = 'block';  
      dots[slideIndex-1].className += ' active';
      setTimeout(showSlides, 5000); // Change image every 2 seconds
      }
      </script>
	  <div style='padding: 30px; height: " . $height . "px; border-left: 6px solid #03dbfc; background-color: #e6ffff;'>";
	  
  	#comment form
	if ($place == $city) {
	  echo "
	    <div id='form_container' style= 'float: left; width: 45%;'>";
	}
	else
	  echo "
        <div>";
	
	echo "
	  <form id='form_18863' class='appnitro'  method='post' action='http://localhost/assignment/twitter/form/twitterPost.php'>
	  <div class='form_description' >
	    <img id='top' src='http://localhost/assignment/twitter/twitterIcon.png' alt='Twitter logo' style='width:50%; height=50%;'>
	    <h2 style='color: #03dbfc; text-align: center;'>Make a comment!</h2>
	    <p style='text-align: center;'>Have you visited this place before? What did you think? Type a comment below and we'll post it to Twitter!</p>
	  </div>						
		<label class='description' for='element_1'><strong>Name: </strong></label>
	  <div>
	    <input id='element_1' name='name' class='element text medium' type='text' maxlength='20' value=''/> 
	  </div> 
	  <br />
	  <label class='description' for='element_2'><strong>Comment: </strong></label>
	    <div>
	      <textarea id='element_2' name='content' class='element textarea small' maxlength='200'></textarea> 
		</div>
		<p class='guidelines' id='guide_2'><small>Max 200 characters</small></p> 
		  <input type='hidden' name='place' value='" . $place . "' />
	      <input type='hidden' name='city' value='" . $city . "' />
          <input id='saveForm' class='button_text' style='background-color: #008CBA; border-radius: 12px;' type='submit'/>
		</form>	
		<!--<div id='footer'>
			Generated by <a href='http://www.phpform.org'>pForm</a>
		</div>--->
	  </div>	
    ";

  # COMMENTS CAROSEL SLIDESHOW
  # 1. Store tweet_id into array

  if ($city != NULL) {
	$query = "SELECT woeid FROM city WHERE name = '" . $city . "'";
    $result = $connection->query($query);
    $woeid = $result->fetch_assoc()['woeid'];  
    $query = "SELECT tweet_id FROM tweet WHERE woeid = " . $woeid . " ORDER BY tweet_id ASC";
    $result = $connection->query($query);
  }
  else {
	$query = "SELECT place_id FROM place WHERE name = '" . $place . "'";
    $result = $connection->query($query);
	$woeid = $result->fetch_assoc()['place_id'];  
    $query = "SELECT tweet_id FROM tweet WHERE place_id = " . $place_id . " ORDER BY tweet_id ASC";
    $result = $connection->query($query);
  }
  
  $ids = array();
  
  while($row = $result->fetch_array()) {
    $ids[] = $row[0];
  }

  $items = array();

  # 2. Store the 10 latest tweets into array
  
  for($x = sizeof($ids) - 1; $x > 0; $x--) {
    $query = "SELECT date_published, author, content FROM tweet WHERE tweet_id = " . $ids[$x] . "";
    $result = $connection->query($query);
    $date_published = $result->fetch_assoc()['date_published'];
	$date_published = substr($date_published, 0, 16);
    $result = $connection->query($query);
    $author = $result->fetch_assoc()['author'];
    $result = $connection->query($query);
    $content = $result->fetch_assoc()['content'];
	
    $items[$x] = "  
      <h4>" . $author . "</h4>
	  <p>" . $content . "</p>
	  <p><em>published: " . $date_published . "</em></p>";
	if (sizeof($items) == 10)
		break;
    }

  # 3. Display tweet data pulled from database cache

  echo "
    <div class='slideshow-container'>
    <br><br><br>
    <h2 style='color: #03dbfc; text-align: center;'>The latest tweets #" . $place . "</h2>
    <!-- The slideshow -->
  ";
  
  foreach ($items as $item) {
    echo"
      <div class='mySlides fade' style='padding: 10px; height: 482px border-left:solid'>
        " . $item . "
      </div>";
  }

  echo "
    </div>
    <br>
    <div style='text-align:center'>";

  # 4. Cycle through array of tweets
  
  for ($x = 0; $x < 10; $x++) {
    $y = $x+1;
    echo "
	  <span class='dot' onclick='currentSlide(" . $y . ")'></span>";
  }
  
  echo "
      </div>
    </div>
    <script>
      var slideIndex = 0;
      showSlides();
    </script>
    </body>
  </html>";
}

#Reference from:
#	https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_slideshow_auto